### ISSUE TITLE
Whiteboard/draw a picture tool disappears in preview quiz question for essay

### ISSUE THREAD

**Issue by kiratskitizing** [justinhunt/moodle-tinymce_poodll#5]
The whiteboard/draw a picture tool disappears when previewing an essay type question.
Please see steps to replicate:
Setup:
Make sure that you have Moodle 3.7 (latest version of that branch).
Make sure to install the latest Poodll Anywhere Tinymce 3.1.0(Build 2018041000).
Edit the TinyMCE settings to include 'poodll' in the toolbar.

1. Create a course.
2. Turn editing on.
3. Check if the Whiteboard tool is now on the toolbar for TinyMCE editor.
4. Click on "Edit" for the Announcements forum.
5. Expand the toolbar and confirm that the Whiteboard tool is there.
6. Go back to the course contents page.
7. Create a quiz activity.
8. Add an Essay question to the quiz.
9. Go to the quiz activity and click "preview" button for the question.
Result: You will notice that the Whiteboard tool is missing.
![Screen Shot 2019-11-07 at 10 02 25 am](https://user-images.githubusercontent.com/16247613/68347137-f00d5c00-0145-11ea-8ae4-eadf7386d04b.png)

**Comment by justinhunt** [comment]
Thanks for the report. I tested this and over here the whiteboard button is displaying ok in the Essay question and in preview mode. Lets check 2 things and admit one thing.

i) Have you selected "HTML Editor with file picker" in the essay question settings? If you have just selected "HTML Editor" the whiteboard should not display because the essay question wouldn't save the drawing file. That would be the correct behaviour.

ii) In the screenshot , it looks like the missing whiteboard toolbar icon might be just off the page, cut off from visibility. Could it really be there and just requires some scrolling?

An admission.
In TInyMCE in full screen mode the Poodll Anywhere tools disappear. Its been a long time, but at the time I was unable to make it work in full screen mode so chose to disable it there. We could revisit that, if it turned out to be the cause of the problem.

**Comment by kiratskitizing** [comment]
Hi Justin,
Thanks for your response. Please see feedback below:
i). I have selected in the Essay question setting (for my initial testing):
Response format: HTML editor 
I have changed it to "HTML editor with file picker".
Result: The whiteboard tool now is displayed.

So just more on the the statement "If you have just selected "HTML Editor" the whiteboard should not display because the essay question wouldn't save the drawing file. That would be the correct behaviour."
Is this because of how Moodle essay question with HTML editor handles the contents? And it can't save handle the whiteboard drawing?

Thanks a lot.

**Comment by justinhunt** [comment]
Yes that is correct. Poodll Anywhere will save the file in the draft files area provided by the essay question, but if it is not "HTML editor with file picker" the essay question will not save those draft area files to permanent storage.

You will notice in this scenario that though the "image" and "media" icons are available on the toolbar, that when you open them you only have the option to paste a link, and not to use the repository system. This is for the same reason.

**Comment by kiratskitizing** [comment]
Hi Justin,
Thanks for the clarifications. I am now closing this as it is functioning as designed.
Regards,
